#include "network.h"

// ... Библиотека для сетевых операций ...

Response sendHTTPRequest(const string& url, const string& method, const Map<string, string>& data) {
  // ... Логика отправки HTTP-запроса ...
}

// ... Другие функции для сетевых операций ...
